-- 02_constraints.sql
-- Reconstructed from the original university project PDF.
-- Referential actions and CHECK constraints follow the documented project rules.

ALTER TABLE RECAPITI
    ADD CONSTRAINT FK_RECAPITI_NEGOZI
    FOREIGN KEY (UsernameNegozio)
    REFERENCES NEGOZI (Username)
    ON DELETE CASCADE;

ALTER TABLE OFFERTE
    ADD CONSTRAINT FK_OFFERTE_NEGOZI
    FOREIGN KEY (UsernameNegozio)
    REFERENCES NEGOZI (Username)
    ON DELETE CASCADE;

ALTER TABLE IMMAGINI
    ADD CONSTRAINT FK_IMMAGINI_PRODOTTI
    FOREIGN KEY (CodProdotto)
    REFERENCES PRODOTTI (Codice)
    ON DELETE CASCADE;

ALTER TABLE PROMOZIONI
    ADD CONSTRAINT FK_PROMOZIONI_PRODOTTI
    FOREIGN KEY (CodProdotto)
    REFERENCES PRODOTTI (Codice)
    ON DELETE CASCADE;

ALTER TABLE PROMOZIONI
    ADD CONSTRAINT FK_PROMOZIONI_OFFERTE
    FOREIGN KEY (CodOfferte)
    REFERENCES OFFERTE (Codice)
    ON DELETE CASCADE;

ALTER TABLE VISUALIZZAZIONI
    ADD CONSTRAINT FK_VISUALIZZAZIONI_CLIENTI
    FOREIGN KEY (UsernameCliente)
    REFERENCES CLIENTI (Username)
    ON DELETE CASCADE;

ALTER TABLE VISUALIZZAZIONI
    ADD CONSTRAINT FK_VISUALIZZAZIONI_OFFERTE
    FOREIGN KEY (CodOfferte)
    REFERENCES OFFERTE (Codice)
    ON DELETE CASCADE;

ALTER TABLE VISUALIZZAZIONI
    ADD CONSTRAINT CK_VOTO
    CHECK (Voto BETWEEN 1 AND 10);

ALTER TABLE OFFERTE
    ADD CONSTRAINT CK_DATE_OFFERTE
    CHECK (DataFine >= DataInizio);

ALTER TABLE OFFERTE
    ADD CONSTRAINT CK_SCONTO_OFFERTE
    CHECK (PercentualeSconto BETWEEN 5 AND 95);

ALTER TABLE OFFERTE
    ADD CONSTRAINT CK_HASHTAG
    CHECK (Hashtag LIKE '#%');

ALTER TABLE IMMAGINI
    ADD CONSTRAINT CK_DIMENSIONE_IMMAGINE
    CHECK (Dimensione > 0);

ALTER TABLE PRODOTTI
    ADD CONSTRAINT CK_PREZZO_PRODOTTO
    CHECK (Prezzo > 0);

ALTER TABLE PROMOZIONI
    ADD CONSTRAINT CK_PREZZO_SCONTATO
    CHECK (PrezzoScontato > 0);
